services:
  - type: web
    name: esention-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: NODE_ENV
        value: production
      - key: APP_URL
        sync: false
    autoDeploy: true
    healthCheckPath: /health 